version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd
    restart: always
    container_name: etcd
    network_mode: bridge
    command:
    - /usr/local/bin/etcd
    - --data-dir=/etcd-data
    - --name
    - node1
    - --initial-advertise-peer-urls
    - http://0.0.0.0:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --advertise-client-urls
    - http://0.0.0.0:2379
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --initial-cluster
    - node1=http://0.0.0.0:2380
    ports:
      - 2379
      - 2380
  grpc:
    container_name: grpc
    build: ./grpc-server
    restart: always
    network_mode: bridge
    ports:
      - "9988:9988"
    depends_on:
      - etcd
  web:
    container_name: web
    build: ./web
    restart: always
    network_mode: bridge
    ports:
      - "9989:9989"
    depends_on:
      - etcd
      - grpc
