version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd
    restart: always
    container_name: etcd
    network_mode: bridge
    ports:
      - 2379
      - 2380
  grpc:
    container_name: grpc
    build: ./grpc
    restart: always
    network_mode: bridge
    ports:
      - "9988:9988"
    depends_on:
      - etcd
  web:
    container_name: web
    build: ./web
    restart: always
    network_mode: bridge
    ports:
      - "9989:9989"
    depends_on:
      - etcd
      - grpc
